#!/usr/bin/env bash
alias shutdown='shutdown now'
alias snvim='sudoedit'
alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index

#personal
alias dot="$HOME/dotfiles"

#arduino
alias sketches="$HOME/diego/arduino/sketches"
alias uno-upload="arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:uno"
alias uno-compile="arduino-cli compile --fqbn arduino:avr:uno"
alias serial="arduino-cli serial -p /dev/ttyACM0 -c"
alias orario="kitten icat ~/diego/uni/y2s1/orario.jpg"
