#!/usr/bin/env bash
alias snvim='sudoedit'
alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index
alias cd="z"

#personal
alias dot="$HOME/dotfiles"

alias serial="arduino-cli monitor -c"
alias orario="kitten icat ~/diego/uni/y2s2/orario.jpg"
alias ssd="cd /run/media/dmart/sddiego"
alias ttp="cd /run/media/dmart/sddiego/sketches_2025; nvim"
alias run='processing-java --sketch=`pwd` --run &;sleep 4; i3-msg floating enable;'
