#!/usr/bin/env bash
alias snvim='sudoedit'
alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index
alias cd="z"

#personal
alias dot="$HOME/dotfiles"

alias serial="arduino-cli monitor -c"
alias ssd="cd /run/media/dmart/sddiego"
alias ttp="cd /run/media/dmart/sddiego/sketches_2025; nvim" # time to process !!!!
alias run='processing-java --sketch=`pwd` --run &;sleep 4; i3-msg floating enable;'
alias dsite="nvim ~/diego/projects/website/site"
alias uni="cd ~/diego/uni/y3s2"
alias testmpi="make clean;make;make run_mpi"
alias testcu="make clean;make;make run_cuda_local"
alias vpn="cd ~/downloads/hpc-vpn/; sudo openvpn ~/downloads/hpc-vpn/frontend-hpc-di-UDP4-1194.ovpn"
alias cluster="ssh $username_cluster@192.168.0.102"
alias sync_notes="sh ~/diego/uni/obsidian_notes/pdf_sync.sh"
