-- movement
vim.keymap.set('', '<up>', function () print('you can do it'); end)
vim.keymap.set('', '<down>', function () print('still in hard mode'); end)
vim.keymap.set('', '<left>', function () print('i believe in you'); end)
vim.keymap.set('', '<right>', function () print('you\'re doing great'); end)
vim.keymap.set('n', 'n', 'nzz')
vim.keymap.set('n', 'N', 'Nzz')
vim.keymap.set('', '<C-u>', '<C-u>zz')
vim.keymap.set('', '<C-d>', '<C-d>zz')
vim.keymap.set('n', '<C-h>', '<C-w>h')
vim.keymap.set('n', '<C-j>', '<C-w>j')
vim.keymap.set('n', '<C-k>', '<C-w>k')
vim.keymap.set('n', '<C-l>', '<C-w>l')
vim.keymap.set('n', '<leader>c', ':noh<CR>')

-- open new terminal inside of vim
vim.keymap.set("n", "<leader>st", function()
  -- vim.cmd("cd %:p:h")
  vim.cmd.vnew()
  vim.cmd.term()
  vim.cmd.wincmd("J")
  vim.api.nvim_win_set_height(0,10)
  vim.fn.feedkeys("a")
end)
